# Generated by Django 5.1.5 on 2025-02-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="icon",
            field=models.ImageField(upload_to="media/skills/"),
        ),
    ]
