# Generated by Django 5.1.5 on 2025-02-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_delete_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_photo",
            field=models.ImageField(blank=True, null=True, upload_to="project_photos/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(),
        ),
    ]
