# Generated by Django 5.1.5 on 2025-02-11 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_project_project_photo_alter_project_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_photo",
        ),
    ]
