# Generated by Django 5.1.5 on 2025-02-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_remove_project_project_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_photo",
            field=models.ImageField(blank=True, null=True, upload_to="project_photos/"),
        ),
    ]
