# Generated by Django 5.1.6 on 2026-04-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_delete_certification_delete_project_delete_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(default='Prsent', max_length=50),
        ),
    ]
