# Generated by Django 5.1.5 on 2025-02-06 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_alter_skill_icon"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Education",
        ),
    ]
