# Generated by Django 5.1.6 on 2026-04-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_experience_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(default='Present', max_length=50),
        ),
    ]
