# Generated by Django 5.1.5 on 2025-02-11 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_project_project_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="start_date",
        ),
    ]
