# Generated by Django 5.1.5 on 2025-02-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_project_end_date_project_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certification",
            old_name="issuer",
            new_name="certificate_name",
        ),
        migrations.RenameField(
            model_name="certification",
            old_name="name",
            new_name="issued_by",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="date",
        ),
        migrations.AddField(
            model_name="certification",
            name="month_year",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="certification",
            name="certificate_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
